# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/data/data/24/ZYNQ/CNN _kernel/CNN _kernel.srcs/sources_1/ip/average_pooling_kernel_line/average_pooling_kernel_line.xci
# IP: The module: 'average_pooling_kernel_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/data/data/24/ZYNQ/CNN _kernel/CNN _kernel.srcs/sources_1/ip/average_pooling_kernel_line/average_pooling_kernel_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'average_pooling_kernel_line'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/data/data/24/ZYNQ/CNN _kernel/CNN _kernel.srcs/sources_1/ip/average_pooling_kernel_line/average_pooling_kernel_line.xci
# IP: The module: 'average_pooling_kernel_line' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/data/data/24/ZYNQ/CNN _kernel/CNN _kernel.srcs/sources_1/ip/average_pooling_kernel_line/average_pooling_kernel_line_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'average_pooling_kernel_line'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
